[variables]
NIXPACKS_INSTALL_CMD = "npm install"

[providers.node]
nodeVersion = "22"

[phases.setup]
nixPkgs = ["...", "nodejs", "pango", "cairo", "glib", "nss", "alsa-lib", "atk", "at-spi2-atk", "cups", "dbus", "expat", "libdrm", "libxkbcommon", "mesa", "nspr", "xorg.libX11", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXext", "xorg.libXfixes", "xorg.libXrandr", "xorg.libxcb"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
